config/routes.rb
Rails.application.routes.draw do
  resources :regulatory_informations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/MyModel.rb
require "aws-sdk-core"

class RegulatoryInformationsController < ApplicationController

  dynamodb = Aws::DynamoDB::Client.new

  params = {
      table_name: "REGULATORYINFORMATION",
      key_schema: [
          {
              attribute_name: "nci_id",
              key_type: "HASH"  #Partition key
          },
          {
              attribute_name: "date_created",
              key_type: "RANGE" #Sort key
          },

      ],
      attribute_definitions: [
          {
              attribute_name: "nci_id",
              attribute_type: "S"
          },
          {
              attribute_name: "date_created",
              attribute_type: "S"
          },

      ],
      provisioned_throughput: {
          read_capacity_units: 10,
          write_capacity_units: 10
      }
  }

  begin
    result = dynamodb.create_table(params)
    puts "Created table. Status: " +
             result.table_description.table_status;

  rescue  Aws::DynamoDB::Errors::ServiceError => error
    puts "Unable to create table:"
    puts "#{error.message}"
  end


end

app/models/RegulatoryInformation.rb
class RegulatoryInformation
  include Aws::Record
  include Aws::Record::RecordClassMethods
  include Aws::Record::Query::QueryClassMethods

  set_table_name "#{self.name.underscore}"

  boolean_attr :active, database_attribute_name: 'is_active_flag'
  string_attr :nci_id, hash_key: true
  string_attr :fda_regulated_drug
  string_attr :fda_regulated_device
  string_attr :post_prior_to_approval
  string_attr :ped_postmarket_surv
  string_attr :exported_from_us

end

app/models/concerns/model.rb
def client
  @client ||= Aws::DynamoDB::Client.new(
      region: "localhost",
      access_key_id: "AKIAZ7TTTQQ6GYT6WQA",
      secret_access_key: "yUx5Avm8UGZWfrlgxGUFUfPepnGr8OdWG1Dcy36k",
      endpoint: "http://localhost:8000"
  )
end

app/models/regulatory_information.rb
class RegulatoryInformation
  include Aws::Record
  include Aws::Record::RecordClassMethods
  include Aws::Record::Query::QueryClassMethods

  include ActiveModel::Serializers::JSON
  #include ModelSerializer

  set_table_name "#{self.name.underscore}"

  boolean_attr :active, database_attribute_name: 'is_active_flag'
  string_attr :nci_id, hash_key: true
  string_attr :fda_regulated_drug
  string_attr :fda_regulated_device
  string_attr :post_prior_to_approval
  string_attr :ped_postmarket_surv
  string_attr :exported_from_us
  string_attr :date_created, range_key: true

end

app/controllers/MovieCreateTable.rb
require "aws-sdk-core"

Aws.config.update({
                      region: "us-east-1",
                      endpoint: "http://localhost:8000"
                  })

dynamodb = Aws::DynamoDB::Client.new

params = {
    table_name: "CTRP_FDAAA",
    key_schema: [
        {
            attribute_name: "NCI_ID",
            key_type: "HASH"  #Partition key
        },
        {
            attribute_name: "Studies a U.S. FDA-regulated Drug Product",
            key_type: "RANGE" #Sort key
        }
    ],
    attribute_definitions: [
        {
            attribute_name: "NCI_ID",
            attribute_type: "S"
        },
        {
            attribute_name: "Studies a U.S. FDA-regulated Drug Product",
            attribute_type: "S"
        },

    ],
    provisioned_throughput: {
        read_capacity_units: 10,
        write_capacity_units: 10
    }
}

begin
  result = dynamodb.create_table(params)
  puts "Created table. Status: " +
           result.table_description.table_status;

rescue  Aws::DynamoDB::Errors::ServiceError => error
  puts "Unable to create table:"
  puts "#{error.message}"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def standard_error_message(error)
    logger.error error.message
    render json: error.to_json, status: 500
  end
end

app/controllers/regulatory_informations_controller.rb
require "aws-sdk-core"

class RegulatoryInformationsController < ApplicationController

  # before_action only: [:index] do
  #   #Rails.logger.info "***** Before Calling  ******"
  #   puts "***** Before Calling  ******"
  #   dynamodb = Aws::DynamoDB::Client.new
  #   params = RegulatoryInformation.new()
  # end
  # def index
  #   begin
  #     puts "***** Inside Calling  ******"
  #     result = dynamodb.create_table(params)
  #     puts "Created table. Status: " +
  #              result.table_description.table_status;
  #
  #   rescue  Aws::DynamoDB::Errors::ServiceError => error
  #     puts "Unable to create table:"
  #     puts "#{error.message}"
  #   end
  #
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/regulatory_informations_helper.rb
module RegulatoryInformationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DynoNodb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/regulatory_informations/_form.html.erb
<%= form_for(regulatory_information) do |f| %>
  <% if regulatory_information.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(regulatory_information.errors.count, "error") %> prohibited this regulatory_information from being saved:</h2>

      <ul>
      <% regulatory_information.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nci_id %>
    <%= f.text_field :nci_id %>
  </div>

  <div class="field">
    <%= f.label :fda_regulated_drug %>
    <%= f.text_field :fda_regulated_drug %>
  </div>

  <div class="field">
    <%= f.label :fda_regulated_device %>
    <%= f.text_field :fda_regulated_device %>
  </div>

  <div class="field">
    <%= f.label :post_prior_to_approval %>
    <%= f.text_field :post_prior_to_approval %>
  </div>

  <div class="field">
    <%= f.label :ped_postmarket_surv %>
    <%= f.text_field :ped_postmarket_surv %>
  </div>

  <div class="field">
    <%= f.label :exported_from_us %>
    <%= f.text_field :exported_from_us %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/regulatory_informations/edit.html.erb
<h1>Editing Regulatory Information</h1>

<%= render 'form', regulatory_information: @regulatory_information %>

<%= link_to 'Show', @regulatory_information %> |
<%= link_to 'Back', regulatory_informations_path %>

app/views/regulatory_informations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Regulatory Informations</h1>

<table>
  <thead>
    <tr>
      <th>Nci</th>
      <th>Fda regulated drug</th>
      <th>Fda regulated device</th>
      <th>Post prior to approval</th>
      <th>Ped postmarket surv</th>
      <th>Exported from us</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @regulatory_informations.each do |regulatory_information| %>
      <tr>
        <td><%= regulatory_information.nci_id %></td>
        <td><%= regulatory_information.fda_regulated_drug %></td>
        <td><%= regulatory_information.fda_regulated_device %></td>
        <td><%= regulatory_information.post_prior_to_approval %></td>
        <td><%= regulatory_information.ped_postmarket_surv %></td>
        <td><%= regulatory_information.exported_from_us %></td>
        <td><%= link_to 'Show', regulatory_information %></td>
        <td><%= link_to 'Edit', edit_regulatory_information_path(regulatory_information) %></td>
        <td><%= link_to 'Destroy', regulatory_information, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Regulatory Information', new_regulatory_information_path %>

app/views/regulatory_informations/new.html.erb
<h1>New Regulatory Information</h1>

<%= render 'form', regulatory_information: @regulatory_information %>

<%= link_to 'Back', regulatory_informations_path %>

app/views/regulatory_informations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nci:</strong>
  <%= @regulatory_information.nci_id %>
</p>

<p>
  <strong>Fda regulated drug:</strong>
  <%= @regulatory_information.fda_regulated_drug %>
</p>

<p>
  <strong>Fda regulated device:</strong>
  <%= @regulatory_information.fda_regulated_device %>
</p>

<p>
  <strong>Post prior to approval:</strong>
  <%= @regulatory_information.post_prior_to_approval %>
</p>

<p>
  <strong>Ped postmarket surv:</strong>
  <%= @regulatory_information.ped_postmarket_surv %>
</p>

<p>
  <strong>Exported from us:</strong>
  <%= @regulatory_information.exported_from_us %>
</p>

<%= link_to 'Edit', edit_regulatory_information_path(@regulatory_information) %> |
<%= link_to 'Back', regulatory_informations_path %>